import { VerticalBox, ComboBox, TabWidget, StandardTableView } from "std-widgets.slint";

export global LibraryManagerData {
    in property <[string]> games;
    in property <[[StandardListViewItem]]> profiles;
    in property <[[StandardListViewItem]]> mods;
}

export component LibraryManager inherits Window {
    title: @tr("Manage Library");

    VerticalBox {
        ComboBox {
            model: LibraryManagerData.games;
        }

        TabWidget {
            profile_tab := Tab {
                title: "Profiles";
                StandardTableView {
                    width: 100%;
                    height: 100%;
                    columns: [{ title: "Name" }];
                    rows: LibraryManagerData.profiles;
                }
            }

            mod_tab := Tab {
                title: "Mods";
                StandardTableView {
                    width: 100%;
                    height: 100%;
                    columns: [{ title: "Name" }];
                    rows: LibraryManagerData.mods;
                }
            }

            tools_tab := Tab {
                title: "Tools";
            }
        }
    }
}
