import { VerticalBox, ComboBox, TabWidget, StandardTableView } from "std-widgets.slint";

export global LibraryManagerData {
    in property <[string]> games;
    in property <[[StandardListViewItem]]> profiles;
    in property <[[StandardListViewItem]]> mods;
    in property <[[StandardListViewItem]]> tools;
}

export component LibraryManager inherits Window {
    callback game_changed(int);

    title: @tr("Manage Library");

    VerticalBox {
        game_switcher := ComboBox {
            model: LibraryManagerData.games;
            selected(_) => game_changed(self.current-index);
        }

        TabWidget {
            profiles_tab := Tab {
                title: "Profiles";
                StandardTableView {
                    width: 100%;
                    height: 100%;
                    columns: [{ title: "Name" }];
                    rows: LibraryManagerData.profiles;
                }
            }

            mods_tab := Tab {
                title: "Mods";
                StandardTableView {
                    width: 100%;
                    height: 100%;
                    columns: [{ title: "Name" }];
                    rows: LibraryManagerData.mods;
                }
            }

            tools_tab := Tab {
                title: "Tools";
            }
        }
    }
}
