import { VerticalBox, HorizontalBox, ComboBox, Button, LineEdit } from "std-widgets.slint";
import { LibraryManager } from "library_manager.slint";
import { ModTableView, ModTableData } from "mod_table_view.slint";

export { ModTableData, LibraryManager }

export component App inherits Window {
    callback open_library_manager();

    title: "Barnacle";

    VerticalBox {
        width: 100%;
        height: 100%;

        // Top bar
        // Global context & high-level management
        HorizontalBox {
            Text {
                text: @tr("Game:");
            }

            ComboBox { }

            play_button := Button {
                text: "▶";
            }

            manage_games_button := Button {
                text: "🛠";
            }

            Text {
                text: @tr("Profile:");
            }

            ComboBox { }

            manage_profiles_button := Button {
                text: "🛠";
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            manage_library_button := Button {
                text: @tr("Library");
                clicked => {
                    root.open_library_manager()
                }
            }

            settings_button := Button {
                text: " ";
            }

            notification_button := Button {
                text: " ";
            }
        }

        // Actions row
        // Task-oriented commands relevant to the current profile
        HorizontalBox {
            install_button := Button {
                text: @tr("Install");
            }

            deploy_button := Button {
                text: @tr("Deploy");
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            tools_button := Button {
                text: @tr("Tools");
            }

            manage_tools_button := Button {
                text: "🛠";
            }
        }

        // Search box
        HorizontalBox {
            LineEdit {
                placeholder-text: @tr("Search...");
            }
        }

        // Mod table
        ModTableView { }
    }
}
