import { StandardTableView } from "std-widgets.slint";

export component ModTableView {
    // in property <[ResolvedModEntry]> model;

    StandardTableView {
        columns: [
            { title: "Header 1" },
            { title: "Header 2" },
        ];
        rows: [
            [
                { text: "Item 1" },
                { text: "Item 2" },
            ],
            [
                { text: "Item 1" },
                { text: "Item 2" },
            ],
            [
                { text: "Item 1" },
                { text: "Item 2" },
            ]
        ];
    }
}
